import "@babel/polyfill";
import openingModalWindowCallback from "./modules/openingModalWindowCallback";
import smoothScrollTo from "./modules/smoothScrollTo";
import openingMobileMenu from "./modules/openingMobileMenu";
import topSlider from "./modules/topSlider";
import accordion from "./modules/accordion";
import openingModalWindowApplication from "./modules/openingModalWindowApplication";
import openingModalFeedback from "./modules/openingModalFeedback";
import sliderCarousel from "./modules/sliderСarousel";
import validateForms from "./modules/validateForms";
import sendForms from "./modules/sendForms";

openingModalWindowCallback();
smoothScrollTo();
openingMobileMenu();
topSlider();
accordion();
openingModalWindowApplication();
openingModalFeedback();
sliderCarousel();
validateForms();
sendForms();
